version: "3.9"

services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  backend:
    build:
      context: ./backend
      args:
        - GROUPID=${GROUPID}
        - USERID=${USERID}
    volumes:
      - ./backend/app:/code
    ports:
      - "8000:8000"
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    # command: "/entry_point.sh"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        - GROUPID=${GROUPID}
    volumes:
      - ./frontend/app:/code
    ports:
      - "5173:5173"
    command: "/entry_point.sh"
    depends_on:
      - backend
volumes:
  mysql:
    driver: local
