#!/usr/bin/env bash

# This code is based on https://github.com/laravel/sail/blob/1.x/bin/sail

UNAMEOUT="$(uname -s)"

# Verify operating system is supported...
case "${UNAMEOUT}" in
Linux*) MACHINE=linux ;;
Darwin*) MACHINE=mac ;;
*) MACHINE="UNKNOWN" ;;
esac

if [ "$MACHINE" == "UNKNOWN" ]; then
    echo "Unsupported operating system [$(uname -s)]. Laravel Sail supports macOS, Linux, and Windows (WSL2)." >&2

    exit 1
fi

# Determine if stdout is a terminal...
if test -t 1; then
    # Determine if colors are supported...
    ncolors=$(tput colors)

    if test -n "$ncolors" && test "$ncolors" -ge 8; then
        BOLD="$(tput bold)"
        YELLOW="$(tput setaf 3)"
        GREEN="$(tput setaf 2)"
        NC="$(tput sgr0)"
    fi
fi

function display_help {
    echo "QuattrocLabs Manager"
    echo "--------------------"
    echo
    echo "${YELLOW}Usage:${NC}" >&2
    echo "  manage COMMAND [options] [arguments]"
    echo
    echo "Unknown commands are passed to the docker-compose binary."
    echo
    echo "${YELLOW}docker-compose Commands:${NC}"
    echo "  ${GREEN}manage up${NC}        Start the application"
    echo "  ${GREEN}manage up -d${NC}     Start the application in the background"
    echo "  ${GREEN}manage stop${NC}      Stop the application"
    echo "  ${GREEN}manage restart${NC}   Restart the application"
    echo "  ${GREEN}manage ps${NC}        Display the status of all containers"
    echo
}

# Proxy the "help" command...
if [ $# -gt 0 ]; then
    if [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "--help" ]; then
        display_help
    fi
else
    display_help
fi

# Source the ".env" file so Laravel's environment variables are available...
if [ ! -z "$APP_ENV" ] && [ -f ./.env.$APP_ENV ]; then
    source ./.env.$APP_ENV
elif [ -f ./.env ]; then
    source ./.env
fi
